### ISSUE TITLE
Lack of packaging instructions

### ISSUE THREAD

**Issue by xixipd** [cryptomator/cryptomator-linux#13]
There is no clear compiling instructions in order to build cryptomator fromsources for Linux.
The environment is not easily understandable for the ones who are not familiar with the projects and its dependancies and/or java compilation tools.

**Comment by overheadhunter** [comment]
Just to be sure we're talking about the same thing: Do you have problems _compiling_ or _packaging_ the pre-compiled stuff? This repo is just for packaging the already compiled jars into a distributable format.

All the compiling happens either in the cryptomator repo (for the application itself) or further upstream (e.g. for libraries such as cryptolib).

Since Java uses a package manager, there is no "one script to build them all" solution as with makefiles and system-provided libraries.

**Comment by xixipd** [comment]
hum, understood.
You are right, this is a packaging issue, sorry for the misunderstanding.
The problem is: ok I can compile everything with maven but how to run it on my local linux machine and distribute it on my other linux workstations? I do not even know how to organise the different cryptomator repositories on my local building machine.

**Comment by overheadhunter** [comment]
Well if the Maven build succeeded, you can already run it provided you have some kind of Java 11 JRE installed (such as openjdk-11-jre): Simply unzip the buildkit.zip that is created by Maven and run the included shellscript.

To create the appimage (this is what this repo is for) it would be probably best if I added a build.sh that replicates what CI is doing locally.

**Comment by xixipd** [comment]
Thank you for your comment! Hoewever, I have no build.sh script within the buildkit.zip. I may create an issue for this in the cryptomator repo as this is not in line with the README. What do you think?

A dedicated script for cryptomator-linux would probably be a good idea, and a more detailed instructions within the README would clearly help (detailing how to organize the local directory cryptomator, cryptomator-linux, etc.)

**Comment by infeo** [comment]
The resources should exists under [/main/buildkit/src/main/resources](https://github.com/cryptomator/cryptomator/tree/8f1fd2474666f05e8b861e83fc544129eba31886/main/buildkit/src/main/resources). Are they not there?

**Comment by xixipd** [comment]
nope, and not included within the zip file.

```
ls cryptomator-release-1.4.10/main/buildkit/src/main/resources/
version.txt
```

To highlight my problem to create an appimage:

- I built all the cryptomator repositories
- I cloned the cryptomator-linux
- I extracted the "libs" directory from the zip file cryptomator-release-1.4.10/main/buildkit/target/buildkit-linux.zip into the cryptomator-linux directory to obtain: cryptomator-linux/libs/version.txt, cryptomator-linux/libs/ui-1.4.10.jar, and all the others jar files)
- I launched ./appdir-build.sh

Here is the output:

> Illegal argument [--force]
> Creating app bundle: /home/user/Project/cryptomator-linux/app/Cryptomator
> Warning: No JDK Modules found.
> Exception: java.lang.NullPointerException
> Exception in thread "main" jdk.packager.internal.PackagerException: Error: Bundler "Linux Application Image" (linux.app) failed to produce a bundle.
>         at jdk.packager/jdk.packager.internal.Arguments.generateBundle(Arguments.java:642)
>         at jdk.packager/jdk.packager.internal.Arguments.processArguments(Arguments.java:582)
>         at jdk.packager/jdk.packager.Main.run(Main.java:71)
>         at jdk.packager/jdk.packager.Main.main(Main.java:47)

**Comment by infeo** [comment]
Ahh, i know now where the problem lies! We introduced the start scripts with _version 1.4.12_.

Before we did not had any in the base reporitory.

**Comment by overheadhunter** [comment]
> Hoewever, I have no build.sh script within the buildkit.zip.

No, there is a run script, not a build script. I was talking about adding a build script to _this_ repo.

**Comment by xixipd** [comment]
Thank you for your help!
Indeed, I would be interested having a build script in this repo or a dedicated README to build an appimage.

By now, I can execute the built cryptomator software thank to the linux-launcher script, however I still do not know how to organize the different cryptomator repositories on my local machine (cryptomator and cryptomator-linux) and which  prerequisites are needed to perform the  appimage packaging.
